# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 07:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 7, 40, 14, 873000, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set([('user', 'magazine')]),
        ),
    ]
