# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_auto_20161103_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 10, 2, 52, 8000, tzinfo=utc)),
        ),
    ]
