# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0005_auto_20161103_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 12, 27, 40, 984000, tzinfo=utc)),
        ),
    ]
