# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0007_auto_20161103_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 14, 32, 12, 530000, tzinfo=utc)),
        ),
    ]
