# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0008_auto_20161103_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 17, 4, 51, 913000, tzinfo=utc)),
        ),
    ]
